[project]
name = "adventofcode"
version = "1.22.0"
description = "Solutions for adventofcode, mostly written in the python language"
authors = ["oryon-dominik <oryon@cyberise.de>"]
dependencies = [
    "environs>=11.2.1",
    "fastapi>=0.115.5",
    "httpx>=0.28.0",
    "humanize>=4.11.0",
    "isort>=5.13.2",
    "jupyter>=1.1.1",
    "more-itertools>=10.5.0",
    "numpy>=2.1.3",
    "parse>=1.20.2",
    "playwright>=1.49.0",
    "pytest-rich>=0.1.1",
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
]
requires-python = ">=3.12"

[tool.pytest.ini_options]
minversion = "7.2"
addopts = ""
markers = [
  "wip: Work In Progress",
  "slow: mark a test that takes a long time to run.",
]
console_output_style = "progress"
python_files = "tests.py test_*.py *_tests.py"
norecursedirs = ".git"
